# -*- coding: utf-8 -*-
"""IA1pythonsubmit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w1HWA951m9IFAFDCqkWOuCBSzZwXEoeo
"""

#1

length=float(input("Enter the lenght \n "))
width=float(input("Enter the width \n"))
area=length*width
print("\n The area is ",area,"\n sq units")

#2
height=float(input("Enter the height in m \n "))
weight=float(input("Enter the weight in kg \n"))
bmi=weight/(height*height)
print("\n The BMI is ",bmi)

#3
student_dict={"Anil":96,"Rohan":67,"Sunil":88,"Mohan":95}
print("The student dictionary has the following data \n",student_dict)
print("The student dictionary has the following student names \n",student_dict.keys())
print("The student dictionary has the following scores \n",student_dict.values())

#4
age=int(input("Enter your age \n"))
if age<18:
  print("minor.")
elif age>=18 and age<65:
  print("adult")
else:
  print('senior')

#5

for i in range(1,51):
  if i%2==0:
    print(i)

#6
#let us assume the correct password is 1234
password=1234
def passd(n):
  if n==1234:
    print('correct')
  else:
    b=int(input("enter password"))
    passd(b)

a=int(input("enter password"))
passd(a)

#7

def average(n):
  avg_result=sum(n)/len(n)
  print("the Average amount is \n",avg_result)

my_list=[20,40,60]
average(my_list)

#8

def vowels(s):
  count=0
  for i in s:
    if i in ('a','e','i','o,','u','A','E','I','O','U'):
      count=count+1
  return count
      #print('Total numbers of vowels are \n',count)

a=vowels("true")
print(a)

#9
import datetime as dt
print(dt.date)
print(dt.time)

time

#10
def add(n,m):
  try:
    print(a+b)
  except:
    print("Non numeric Error")

add(3,'sas')

#11
try:
  a=int(input('Enter int number'))
except ValueError():
    print("Not an int value")

#12
def divide(a,b):
  try:
    c=a/b
    print(c)
  except ZeroDivisionError():
    print("Can't divide by zero")

divide(12,2)

#13
file_data="Hello, Python!"

f=open("store_text.txt",'w')
f.write(file_data)
f.close()

#14
f1=open("store_text.txt",'r')
newdata=f1.read()
print(newdata)
f1.close()

#15
file_data="we can start"

f=open("store_text.txt",'w')
f.write(file_data)


f1=open("store_text.txt",'r')
new2=f1.read()
print(new2)