# -*- coding: utf-8 -*-
"""LVADSUSR118_Siddharth_lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AA_LZ1EE4N6mLC-hdwkJs6d_xjRoeFaL
"""

import pandas as pd
from sklearn.ensemble import IsolationForest
import matplotlib.pyplot as plt

df = pd.read_csv("social_network.csv")

df.info()

df.drop_duplicates(inplace=True)

df.dropna()

# Selecting features for anomaly detection
features = ["login_activity", "posting_activity", "social_connections"]

# Creating a new dataframe
X = df[features]

model = IsolationForest()

model.fit(X)

# Predict the anomalies in the data
y_pred = model.predict(X)



df["anomaly_score"] = model.decision_function(X)


anomalies = df.loc[df["anomaly_score"] < 0]

print(anomalies)

anomaly_scores = model.predict(X)
df['Anomaly'] = ['Yes' if score == -1 else 'No' for score in anomaly_scores]
df





